name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Build
      run: go build -v ./...

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.14
      - run: |
          echo "CC_PREFIX=$(go list -m)" >> $GITHUB_ENV
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -coverprofile coverage.out ./...
          coverageLocations: "${{ github.workspace }}/c.out:gocov" # Should be the default, but workarounds this issue
          prefix: ${{ env.CC_PREFIX }} # Makes reporter work with modern gocov reports

  # test:
  #     runs-on: ubuntu-latest
  #     strategy:
  #       fail-fast: false
  #       matrix:
  #         go: ['1.11', '1.12', '1.13', '1.14', '1.15']
  #     steps:
  #       - uses: actions/setup-go@v1
  #         with:
  #           go-version: ${{ matrix.go }}
  #       - uses: actions/checkout@v2
  #       - run: go test -v -coverprofile=profile.cov ./...
