name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@main

    - name: Run unit tests
      run: |
        make clean coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  # test:
  #     runs-on: ubuntu-latest
  #     strategy:
  #       fail-fast: false
  #       matrix:
  #         go: ['1.11', '1.12', '1.13', '1.14', '1.15']
  #     steps:
  #       - uses: actions/setup-go@v1
  #         with:
  #           go-version: ${{ matrix.go }}
  #       - uses: actions/checkout@v2
  #       - run: go test -v -coverprofile=profile.cov ./...
